name: RulePlugin
version: ${project.version}
main: com.nekozouneko.rulePlugin.RulePlugin
api-version: '1.21'
folia-supported: true
author: RunQ
description: ルールを表示するためだけのプラグイン

commands:
  rule:
    description: rule plugin
    permission: rule.rule

permissions:
  rule.*:
    children:
      rule.rule: true
      rule.reload: true
  rule.rule:
    description: show rules
    default: true
  rule.reload:
    description: reload config